---
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluten
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VPNSP=private internet access
      - REGION=US Houston
      - OPENVPN_USER=CHANGEME
      - OPENVPN_PASSWORD=CHANGEME
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
      - 9117:9117
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    restart: unless-stopped
