http:
#region routers
  routers:
    qbittorrent:
      entryPoints:
        - "http"
      rule: "Host(`qbittorrent.local.example.com`)"
      middlewares:
        - https-redirect
      service: qbittorrent
    qbittorrent-secure:
      entryPoints:
        - "https"
      rule: "Host(`qbittorrent.local.example.com`)"
      middlewares:
        - default-headers
      tls: {}
      service: qbittorrent
    jackett:
      entryPoints:
        - "http"
      rule: "Host(`jackett.local.example.com`)"
      middlewares:
        - https-redirect
      service: jackett
    jackett-secure:
      entryPoints:
        - "https"
      rule: "Host(`jackett.local.example.com`)"
      middlewares:
        - default-headers
      tls: {}
      service: jackett
#endregion
#region services
  services:
    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://192.168.0.40:8080"
        passHostHeader: true
    jackett:
      loadBalancer:
        servers:
          - url: "http://192.168.0.40:9117"
        passHostHeader: true
#endregion
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers