---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${defaultStorage}/configs/radarr:/config
      - ${defaultStorage}/storage/movies:/movies
      - ${defaultStorage}/storage/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    external: true